---
apiVersion: v1
kind: Namespace
metadata:
  name: tckt
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tckt
type: Opaque
stringData:
  username: tckt
  password: tcktpass
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tckt
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tckt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: tcktdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: tckt
  namespace: tckt
spec:
  selector:
    app: tckt
  ports:
    - name: http
      port: 80
      targetPort: 8088
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tckt
  namespace: tckt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tckt
  template:
    metadata:
      labels:
        app: tckt
    spec:
      containers:
        - name: tckt
          image: YOUR_REGISTRY/tckt:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/tcktdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

